site: tim-munuhe
url: tim-munuhe.github.io
title: tim-munuhe
description:
markdown: kramdown

twitter:
  username: "tim_munuhe"
  card: summary
  creator: "tim_munuhe"
author:
  twitter: "tim_munuhe"
  name: "Timothy W. Munuhe, Ph.D."
  avatar:
  email: "timothy.munuhe@gmail.com"
  url: "tim-munuhe.gitub.io"
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
